name: sync-homebrew

on:
  workflow_dispatch:

jobs:
  bump-casks:
    runs-on: macos-latest
    steps:
    - uses: macauley/action-homebrew-bump-cask@v1
      with:
        token: ${{secrets.GH_TOKEN}}
        org: viarotel-org
        tap: viarotel-org/homebrew-escrcpy
        cask: escrcpy
        livecheck: true
        dryrun: false